-- ── Objective Submissions ────────────────────────────────────────────────
-- AI Act compliance: High-Risk AI System (employment/performance) - Annex III
-- Art. 12 (record-keeping), Art. 13 (transparency), Art. 14 (human oversight)

CREATE TABLE IF NOT EXISTS objective_submissions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Art. 12: temporal traceability
  submitted_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  year                INTEGER NOT NULL DEFAULT 2026,

  -- Art. 13: subject identification
  employee_name       TEXT NOT NULL,
  job_title           TEXT,
  department          TEXT,
  country_code        TEXT,
  country_label       TEXT,
  archetype_code      TEXT,
  archetype_label     TEXT,
  manager_name        TEXT,

  -- Art. 11: AI system technical documentation
  ai_model            TEXT NOT NULL DEFAULT 'claude-haiku-4-5-20251001',
  ai_used             BOOLEAN NOT NULL DEFAULT TRUE,

  -- Art. 13: explainability — portfolio-level AI reasoning
  portfolio_score     INTEGER,
  portfolio_summary   TEXT,

  -- Art. 14: human oversight evidence
  objectives_total    INTEGER,
  objectives_ai       INTEGER,   -- generated by Delfos
  objectives_manual   INTEGER,   -- written by the employee
  objectives_improved INTEGER,   -- AI-generated then improved via "Ask Delfos"
  objectives_ignored  INTEGER,   -- employee chose to ignore

  -- Workflow status (human approval gate — not AI)
  status              TEXT NOT NULL DEFAULT 'pending_approval'
    CHECK (status IN ('pending_approval', 'approved', 'rejected', 'revision_requested'))
);

-- ── Submitted Objectives ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS submitted_objectives (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id   UUID NOT NULL REFERENCES objective_submissions(id) ON DELETE CASCADE,
  seq             INTEGER NOT NULL,  -- position in the portfolio (1–5)

  -- Content
  title           TEXT NOT NULL,
  description     TEXT,
  type            TEXT NOT NULL DEFAULT 'performance',
  key_results     JSONB,
  by_when         TEXT,
  metric          TEXT,
  value_statement TEXT,

  -- Art. 14: human oversight — was this AI or human authored?
  source          TEXT NOT NULL DEFAULT 'user' CHECK (source IN ('delfos', 'user')),

  -- Art. 13: explainability — AI scoring rationale
  score           INTEGER,
  weight          INTEGER,
  feedback        TEXT,        -- AI coaching note
  coaching_tips   JSONB,
  linked_cascades JSONB,
  sub_scores      JSONB        -- { role_fit, impact, relevance, ambition, measurability, smart }
);

-- ── RLS Policies ─────────────────────────────────────────────────────────
ALTER TABLE objective_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE submitted_objectives  ENABLE ROW LEVEL SECURITY;

-- Anon can insert (no auth yet — Entra ID pending)
CREATE POLICY "anon_insert_submissions"
  ON objective_submissions FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "anon_insert_objectives"
  ON submitted_objectives FOR INSERT TO anon WITH CHECK (true);

-- Anon can read (needed for manager dashboard later)
CREATE POLICY "anon_read_submissions"
  ON objective_submissions FOR SELECT TO anon USING (true);

CREATE POLICY "anon_read_objectives"
  ON submitted_objectives FOR SELECT TO anon USING (true);
